Fixed removal of z_impl_clock_gettime in zephyr 3.5.99
eProsima/Micro-XRCE-DDS-Client pull request #378
Opened 2024-01-12 12:11 UTC by danielallstar

Solution to the following problem: https://github.com/micro-ROS/micro_ros_zephyr_module/issues/134

The notified problem is: " in function uxr_nanos': undefined reference to z_impl_clock_gettime' "
The Zephyr developers have removed the `z_impl_clock_gettime' function and replaced it by the clock_gettime function.
I have implemented the new function in the time.c file, while maintaining compatibility with the older zephyr versions.

2024-01-12 17:08 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Linux&build=606)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/606/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Windows&build=625)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/625/)

2024-01-15 06:36 UTC, pablogs9 commented
The CI is failing due to uncrustify failure, you can fix it using the following operation inside the folder and pushing the changes.

```
# Install uncrustify
# git clone https://github.com/uncrustify/uncrustify --branch uncrustify-0.72.0 --single-branch uncrustify
# mkdir -p uncrustify/build
# cd uncrustify/build
# cmake -DCMAKE_INSTALL_PREFIX=../install ..
# make -j$(nproc)
# cd ../..
# export PATH=${PWD}/uncrustify/install/bin:$PATH

# Get the config and check
curl -l https://raw.githubusercontent.com/eProsima/cpp-style/master/uncrustify.cfg -o uncrustify.cfg
find src test include examples \( -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \) -exec uncrustify -c uncrustify.cfg --check {} +
```

2024-01-16 08:38 UTC, danielallstar commented
After running the crustify operation inside the folder, git does not see any changes to commit. This does not seem to be the expected behavior. What do you suggest to do now?

2024-01-16 08:42 UTC, pablogs9 commented
Sorry I did not write the correct command, instead of `--check` use `--no-backup` in `uncrustify` command

2024-01-16 11:15 UTC, pablogs9 requested changes

2024-01-16 14:28 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Linux&build=607)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/607/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Windows&build=627)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/627/)

2024-01-19 07:55 UTC, pablogs9 commented
Testing here: https://github.com/micro-ROS/micro_ros_zephyr_module/pull/136

2024-01-19 08:13 UTC, pablogs9 commented
https://github.com/micro-ROS/micro_ros_zephyr_module/pull/136 is green, so I merge this.

@danielallstar thanks a lo for the contribution!

2024-01-19 08:19 UTC, merged

2024-01-19 08:24 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Linux&build=608)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/608/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Windows&build=628)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/628/)