[21890] Update commercial support section in project README
eProsima/Micro-XRCE-DDS-Client pull request #390
Opened 2024-10-15 10:57 UTC by JesusPoderoso

This PR updates this project README's commercial support section

2024-10-15 11:02 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Linux&build=622)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/622/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Windows&build=642)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/642/)

2024-10-17 06:29 UTC, LuciaEchevarria99 requested changes

2024-10-17 06:29 UTC, LuciaEchevarria99 commented on README.md
The `Getting Help` section needs to be deleted

2024-10-17 07:09 UTC, LuciaEchevarria99 approved these changes
LGTM

2024-10-17 07:11 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Linux&build=623)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/623/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS-Client%20Manual%20Windows&build=643)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/643/)

2024-10-17 07:11 UTC, merged